name: QA Flutter Web Deploy
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }} commit is running
on:
  workflow_dispatch:

jobs:
  find-latest-version:
    uses: ./.github/workflows/TemplateGetLatestVersion.yml
    secrets:
      repoToken: ${{ secrets.REPO_READ_TOKEN }}
  qa-flutter-flow-web-deploy:
    uses: ./.github/workflows/TemplateFlutterWebDeploy.yml
    needs: find-latest-version
    with:
      versionToBuild: ${{ needs.find-latest-version.outputs.latest_version }}
    secrets:
      repoToken: ${{ secrets.REPO_READ_TOKEN }}