name: Get Repo Latest Version
on:
  workflow_call:
    secrets:
      repoToken:
        required: true
    outputs:
      latest_version: ${{ steps.get_version.outputs.latest_version }}

jobs:
  FlutterFlowWebBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check out only flutterFlow web folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ on.workflow_call.secrets.repoToken }}
          fetch-depth: 1
          sparse-checkout: '.gitignore'
          sparse-checkout-cone-mode: false
          ref : test_server_deploy

      - name: Get latest version
        id: get_version
        run: |
          latest_version=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Output latest version
        run: echo "The latest version is ${{ env.latest_version }}"