name: Template Flutter Web Build
on:
  workflow_call:
    inputs:
      versionToBuild:
        required: true
        type: string
    secrets:
      repoToken:
        required: true
      ec2IP:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretKey:
        required: true
      awsRegion: 
        required: true
      ec2User:
        required: true
      secuityGroupId:
        required: true
      sshKey:
        required: true

jobs:
  FlutterFlowWebBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check out only flutterFlow web folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.repoToken }}
          fetch-depth: 1
          sparse-checkout: 'flutterFlow/magnum'
          sparse-checkout-cone-mode: false
          ref : test_server_deploy
          version: ${{ inputs.versionToBuild }}
            
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - run: |
          cd flutterFlow/magnum
          sed -i 's|<base href="/">|<base href="/flutterflow/">|' web/index.html
          flutter clean
          flutter pub get         
          flutter build web --release --web-renderer html
          
      - name: Brotli compress
        run: |
          sudo apt-get  -y install brotli
          cd flutterFlow/magnum/build/web
          rm -rf canvaskit
          find ./ -type f -exec brotli -jZv {} \;
          
      - run: |
          cd flutterFlow/magnum/build/
          zip -r web.zip web

      - uses: WonderWhyDev/copy-to-ec2-action@317e451c466aa97158ca3f646121399f005343a7
        with:
           ec2IP: ${{ secrets.ec2IP }}
           awsAccessKeyId: ${{ secrets.awsAccessKeyId }}
           awsSecretKey: ${{ secrets.awsSecretKey }}
           awsRegion: ${{ secrets.awsRegion }}
           ec2User: ${{ secrets.ec2User }}
           secuityGroupId: ${{ secrets.secuityGroupId }}
           sshKey: ${{ secrets.sshKey }}
           fileToCopy: flutterFlow/magnum/build/web.zip
           destination: ~/web.zip
           cleanUpdestination: ~/
           unzipDestination: ~/

