name: Test server Terraform Deploy
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }} commit is running
on:
  workflow_dispatch:

jobs:
  TerraFormPlanning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          path: wonderWhy
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform Apply
        run: |
          cd wonderWhy          
          echo "export AWS_ACCESS_KEY_ID= ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}" >> ~/.bashrc
          echo "export AWS_SECRET_ACCESS_KEY= ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}" >> ~/.bashrc
          source ~/.bashrc
          docker-compose run terra terragrunt init -upgrade
          docker-compose run terra terragrunt plan

  TerraFormApplyAndCopyingToS3:
    runs-on: ubuntu-latest
    needs: TerraFormPlanning
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          path: wonderWhy
          token: ${{ secrets.REPO_READ_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform Apply
        run: |
          cd wonderWhy          
          echo "export AWS_ACCESS_KEY_ID= ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}" >> ~/.bashrc
          echo "export AWS_SECRET_ACCESS_KEY= ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}" >> ~/.bashrc
          source ~/.bashrc
          docker-compose run terra terragrunt apply -auto-approve
     
      - name: Saving state in s3
        run: |
         aws s3 cp /home/runner/work/deploy/deploy/wonderWhy/deploy/terra/env/test/app/terraform.tfstate s3://terragruntstates/testserver
         aws s3 cp /home/runner/work/deploy/deploy/wonderWhy/deploy/terra/env/test/app/terraform.tfstate.backup s3://terragruntstates/testserver