name: Test Ground
on:
 workflow_dispatch:

jobs:
  FlutterFlowWebBuild:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch index.html
          touch bla.js
          zip -r web.zip web
      - uses: WonderWhyDev/copy-to-ec2-action@91fde10803f7b1986f28f64f730afd509926d51e
        with:
           ec2IP: 52.4.164.231
           awsAccessKeyId: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
           awsSecretKey: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
           awsRegion: us-east-1
           ec2User: ec2-user
           secuityGroupId: sg-0109e0cf4e941e2f5
           sshKey: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
           fileToCopy: web.zip
           destination: ~/
           unzipDestination: /tmp/
