name: Test Ground
on:
 workflow_dispatch:

jobs:
  FlutterFlowWebBuild:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get  -y install brotli
          brotli --help
          touch index.html
          touch bla.js
          for FILE_EXT in '.js' '.css' '*.html'; do find $DIR -type f -path $FILE_EXT | { [ -z "(cat)" ] && echo "no FILE_EXT files found" || echo "$(cat)" | xargs /brotli -v --; }; done
